### ISSUE TITLE
How to add per-scene fine-tuning to the code

### ISSUE THREAD

**Issue by 1015904089** [donydchen/matchnerf#1]

**Comment by donydchen** [comment]
Hi @1015904089 , thanks for your interest in our work.

To perform per-scene fine-tuning, we mainly adopt the design of MVSNeRF. In particular, we also perform fine-tuning on a 'Neural Encoding Volume' similar to MVSNeRF, with the exception that it is initialised with our learned correspondence matching information as opposed to the original cost volume.

Note that MatchNeRF is designed for *generalizing* to unseen scenes, whereas per-scene fine-tuning is not our current priority. We will find time in the future to clean and update our per-scene fine-tuning codes.
