### ISSUE TITLE
dtu and intrinsics

### ISSUE THREAD

**Issue by smallpeachofchangan** [donydchen/matchnerf#3]
hello, why the intrinsics need *4?, and how the w/2 and h/2 are not the half of the pixel of images? thank you

**Comment by donydchen** [comment]
Hi @smallpeachofchangan , the camera intrinsics are obtained from the preprocessed DTU dataset (in 640x512), where the authors store the intrinsics used for building the 1/4 resolution (in 160x128) cost volumes. Therefore, we need to multiply it by 4 to rescale it back to the image resolution of 640x512.

Specifically, the provided intrinsic is 
```
361.54125 0.0 82.900625 
0.0 360.3975 66.383875 
0.0 0.0 1.0 
```
and multiply the first two rows by 4 (https://github.com/donydchen/matchnerf/blob/main/datasets/dtu.py#L96) will make it into
```
1446.165 0.0 331.6025
0.0 1441.59 265.5355
0.0 0.0 1.0 
```
Here (331.6025, 265.5355) are roughly (320, 256), which is half of the image resolutions as expected. Hope it clear, thanks.

**Comment by smallpeachofchangan** [comment]
> Hi @smallpeachofchangan , the camera intrinsics are obtained from the preprocessed DTU dataset (in 640x512), where the authors store the intrinsics used for building the 1/4 resolution (in 160x128) cost volumes. Therefore, we need to multiply it by 4 to rescale it back to the image resolution of 640x512.
> 
> Specifically, the provided intrinsic is
> 
> ```
> 361.54125 0.0 82.900625 
> 0.0 360.3975 66.383875 
> 0.0 0.0 1.0 
> ```
> 
> and multiply the first two rows by 4 (https://github.com/donydchen/matchnerf/blob/main/datasets/dtu.py#L96) will make it into
> 
> ```
> 1446.165 0.0 331.6025
> 0.0 1441.59 265.5355
> 0.0 0.0 1.0 
> ```
> 
> Here (331.6025, 265.5355) are roughly (320, 256), which is half of the image resolutions as expected. Hope it clear, thanks.

Thank you for you reply! It is clear.
